apiVersion: cdn.azure.upbound.io/v1beta1
kind: FrontdoorRoute
metadata:
  annotations:
    meta.upbound.io/example-id: cdn/v1beta1/frontdoorroute
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    cdnFrontdoorEndpointIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    cdnFrontdoorOriginGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    cdnFrontdoorOriginIdsSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    enabled: true
    forwardingProtocol: HttpsOnly
    httpsRedirectEnabled: true
    linkToDefaultDomain: true
    patternsToMatch:
      - /*
    supportedProtocols:
      - Http
      - Https
---
apiVersion: cdn.azure.upbound.io/v1beta1
kind: FrontdoorEndpoint
metadata:
  annotations:
    meta.upbound.io/example-id: cdn/v1beta1/frontdoorendpoint
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    cdnFrontdoorProfileIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    tags:
      ENV: example
---
apiVersion: cdn.azure.upbound.io/v1beta1
kind: FrontdoorOrigin
metadata:
  annotations:
    meta.upbound.io/example-id: cdn/v1beta1/frontdoororigin
  labels:
    testing.upbound.io/example-name: example
  name: example2
spec:
  forProvider:
    cdnFrontdoorOriginGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    certificateNameCheckEnabled: false
    enabled: true
    hostName: linuxwebappslot-lwa2.azurewebsites.net
    httpPort: 80
    httpsPort: 443
    originHostHeader: linuxwebappslot-lwa2.azurewebsites.net
    priority: 2
    weight: 1

---
apiVersion: cdn.azure.upbound.io/v1beta1
kind: FrontdoorOrigin
metadata:
  annotations:
    meta.upbound.io/example-id: cdn/v1beta1/frontdoororigin
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    cdnFrontdoorOriginGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    certificateNameCheckEnabled: false
    enabled: true
    hostName: linuxwebappslot-lwa.azurewebsites.net
    httpPort: 80
    httpsPort: 443
    originHostHeader: linuxwebappslot-lwa.azurewebsites.net
    priority: 1
    weight: 1
---
apiVersion: cdn.azure.upbound.io/v1beta1
kind: FrontdoorOriginGroup
metadata:
  annotations:
    meta.upbound.io/example-id: cdn/v1beta1/frontdoororigin
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    cdnFrontdoorProfileIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    loadBalancing:
    - {}
---
apiVersion: cdn.azure.upbound.io/v1beta1
kind: FrontdoorProfile
metadata:
  annotations:
    meta.upbound.io/example-id: cdn/v1beta1/frontdoororigin
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    resourceGroupNameSelector:
      matchLabels:
        azure.platformref.upbound.io/network-id: ref-azure-network-from-xr
    skuName: Standard_AzureFrontDoor
